var chemical_table = {
    "H" : { "quality": 1.0079, "proton": 1 , "cn": "氢"},
    "Li": { "quality": 6.94  , "proton": 3 , "cn": "锂", "group": "alkali"},
    "Na": { "quality": 22.990, "proton": 11, "cn": "钠", "group": "alkali"},
    "K" : { "quality": 39.098, "proton": 19, "cn": "钾", "group": "alkali"},
    "Rb": { "quality": 85.468, "proton": 37, "cn": "铷", "group": "alkali"},
    "Cs": { "quality": 132.91, "proton": 55, "cn": "铯", "group": "alkali"},
    "Fr": { "quality": 223   , "proton": 87, "cn": "钫", "group": "alkali"},

    "Be": { "quality": 9.0122, "proton": 4  , "cn": "铍", "group": "alkaline"},
    "Mg": { "quality": 24.305, "proton": 12 , "cn": "镁", "group": "alkaline"},
    "Ca": { "quality": 40.078, "proton": 20 , "cn": "钙", "group": "alkaline"},
    "Sr": { "quality": 87.62 , "proton": 38 , "cn": "锶", "group": "alkaline"},
    "Ba": { "quality": 137.33, "proton": 56 , "cn": "钡", "group": "alkaline"},
    "Ra": { "quality": 226   , "proton": 88 , "cn": "镭", "group": "alkaline"},

    "Sc": { "quality": 44.956, "proton": 21 , "cn": "钪", "group": "transition"},
    "Y" : { "quality": 88.906, "proton": 39 , "cn": "钇", "group": "transition"},
    "La-Lu": {"quality": "" , "proton": "", "cn": "镧系", "group": "none"},
    "Ac-Lr": {"quality": "" , "proton": "", "cn": "镧系", "group": "none"},
    "La": { "quality": 138.91, "proton": 57 , "cn": "镧", "group": "transition"},
    "Ce": { "quality": 140.12, "proton": 58 , "cn": "铈", "group": "transition"},
    "Pr": { "quality": 140.91, "proton": 59 , "cn": "镨", "group": "transition"},
    "Nd": { "quality": 144.24, "proton": 60 , "cn": "钕", "group": "transition"},
    "Pm": { "quality": 145   , "proton": 61 , "cn": "钷", "group": "transition"},
    "Sm": { "quality": 150.36, "proton": 62 , "cn": "钐", "group": "transition"},
    "Eu": { "quality": 151.96, "proton": 63 , "cn": "铕", "group": "transition"},
    "Gd": { "quality": 157.25, "proton": 64 , "cn": "钆", "group": "transition"},
    "Tb": { "quality": 158.93, "proton": 65 , "cn": "铽", "group": "transition"},
    "Dy": { "quality": 162.50, "proton": 66 , "cn": "镝", "group": "transition"},
    "Ho": { "quality": 164.93, "proton": 67 , "cn": "钬", "group": "transition"},
    "Er": { "quality": 167.26, "proton": 68 , "cn": "铒", "group": "transition"},
    "Tm": { "quality": 168.93, "proton": 69 , "cn": "铥", "group": "transition"},
    "Yb": { "quality": 173.05, "proton": 70 , "cn": "镱", "group": "transition"},
    "Lu": { "quality": 174.97, "proton": 71 , "cn": "镥", "group": "transition"},

    "Ac": { "quality": 227   , "proton": 89 , "cn": "锕", "group": "transition"},
    "Th": { "quality": 232.04, "proton": 90 , "cn": "钍", "group": "transition"},
    "Pa": { "quality": 231.04, "proton": 91 , "cn": "镤", "group": "transition"},
    "U":  { "quality": 238.03, "proton": 92 , "cn": "铀", "group": "transition"},
    "Np": { "quality": 237   , "proton": 93 , "cn": "镎", "group": "transition"},
    "Pu": { "quality": 244   , "proton": 94 , "cn": "钚", "group": "transition"},
    "Am": { "quality": 243   , "proton": 95 , "cn": "镅", "group": "transition"},
    "Cm": { "quality": 247   , "proton": 96 , "cn": "锔", "group": "transition"},
    "Bk": { "quality": 247   , "proton": 97 , "cn": "锫", "group": "transition"},
    "Cf": { "quality": 251   , "proton": 98 , "cn": "锎", "group": "transition"},
    "Es": { "quality": 252   , "proton": 99 , "cn": "锿", "group": "transition"},
    "Fm": { "quality": 257   , "proton": 100, "cn": "镄", "group": "transition"},
    "Md": { "quality": 258   , "proton": 101, "cn": "钔", "group": "transition"},
    "No": { "quality": 259   , "proton": 102, "cn": "锘", "group": "transition"},
    "Lr": { "quality": 266   , "proton": 103, "cn": "铹", "group": "transition"},

    "Ti": { "quality": 47.867, "proton": 22 , "cn": "钛", "group": "transition"},
    "Zr": { "quality": 91.224, "proton": 40 , "cn": "锆", "group": "transition"},
    "Hf": { "quality": 178.49, "proton": 72 , "cn": "铪", "group": "transition"},
    "Rf": { "quality": 267   , "proton": 104, "cn": "鈩", "group": "transition"},

    "V" : { "quality": 50.942, "proton": 23 , "cn": "钒", "group": "transition"},
    "Nb": { "quality": 92.906, "proton": 41 , "cn": "铌", "group": "transition"},
    "Ta": { "quality": 180.95, "proton": 73 , "cn": "钽", "group": "transition"},
    "Db": { "quality": 268   , "proton": 105, "cn": "𬭊", "group": "transition"},

    "Cr": { "quality": 51.996, "proton": 24 , "cn": "铬", "group": "transition"},
    "Mo": { "quality": 95.95 , "proton": 42 , "cn": "钼", "group": "transition"},
    "W" : { "quality": 183.84, "proton": 74 , "cn": "钨", "group": "transition"},
    "Sg": { "quality": 269   , "proton": 106, "cn": "𨭎", "group": "transition"},

    "Mn": { "quality": 54.938, "proton": 25 , "cn": "锰", "group": "transition"},
    "Tc": { "quality": 98    , "proton": 43 , "cn": "锝", "group": "transition"},
    "Re": { "quality": 186.21, "proton": 75 , "cn": "铼", "group": "transition"},
    "Bh": { "quality": 270   , "proton": 107, "cn": "𬭛", "group": "transition"},

    "Fe": { "quality": 55.845, "proton": 26 , "cn": "铁", "group": "transition"},
    "Ru": { "quality": 101.07, "proton": 44 , "cn": "钌", "group": "transition"},
    "Os": { "quality": 190.23, "proton": 76 , "cn": "锇", "group": "transition"},
    "Hs": { "quality": 277   , "proton": 108, "cn": "𬭶", "group": "transition"},

    "Co": { "quality": 58.933, "proton": 27 , "cn": "钴", "group": "transition"},
    "Rh": { "quality": 102.91, "proton": 45 , "cn": "铑", "group": "transition"},
    "Ir": { "quality": 192.22, "proton": 77 , "cn": "铱", "group": "transition"},
    "Mt": { "quality": 278   , "proton": 109, "cn": "鿏", "group": "transition"},

    "Ni": { "quality": 58.693, "proton": 28 , "cn": "镍", "group": "transition"},
    "Pd": { "quality": 106.42, "proton": 46 , "cn": "钯", "group": "transition"},
    "Pt": { "quality": 195.08, "proton": 78 , "cn": "铂", "group": "transition"},
    "Ds": { "quality": 281   , "proton": 110, "cn": "鐽", "group": "transition"},

    "Cu": { "quality": 63.546, "proton": 29 , "cn": "铜", "group": "transition"},
    "Ag": { "quality": 107.87, "proton": 47 , "cn": "银", "group": "transition"},
    "Au": { "quality": 196.97, "proton": 79 , "cn": "金", "group": "transition"},
    "Rg": { "quality": 282   , "proton": 111, "cn": "錀", "group": "transition"},

    "Zn": { "quality": 65.38 , "proton": 30 , "cn": "锌", "group": "transition"},
    "Cd": { "quality": 112.41, "proton": 48 , "cn": "镉", "group": "transition"},
    "Hg": { "quality": 200.59, "proton": 80 , "cn": "汞", "group": "transition"},
    "Cn": { "quality": 285   , "proton": 112, "cn": "鎶", "group": "transition"},

    "B" : { "quality": 10.81 , "proton": 5  , "cn": "硼", "group": "metalloid"},
    "Al": { "quality": 26.982, "proton": 13 , "cn": "铝", "group": "metalloid"},
    "Ga": { "quality": 69.723, "proton": 31 , "cn": "镓", "group": "metalloid"},
    "In": { "quality": 114.82, "proton": 49 , "cn": "铟", "group": "metalloid"},
    "Tl": { "quality": 204.38, "proton": 81 , "cn": "铊", "group": "metalloid"},
    "Nh": { "quality": 286   , "proton": 113, "cn": "鉨", "group": "metalloid"},

    "C" : { "quality": 12.011, "proton": 6  , "cn": "碳", "group": "nonmetal"},
    "Si": { "quality": 28.085, "proton": 14 , "cn": "硅", "group": "metalloid"},
    "Ge": { "quality": 72.630, "proton": 32 , "cn": "锗", "group": "metalloid"},
    "Sn": { "quality": 118.71, "proton": 50 , "cn": "锡", "group": "metalloid"},
    "Pb": { "quality": 207.2 , "proton": 82 , "cn": "铅", "group": "metalloid"},
    "Fl": { "quality": 289   , "proton": 114, "cn": "鈇", "group": "metalloid"},

    "N" : { "quality": 14.007, "proton": 7  , "cn": "氮", "group": "nonmetal"},
    "P" : { "quality": 30.974, "proton": 15 , "cn": "磷", "group": "nonmetal"},
    "As": { "quality": 74.922, "proton": 33 , "cn": "砷", "group": "metalloid"},
    "Sb": { "quality": 121.76, "proton": 51 , "cn": "锑", "group": "metalloid"},
    "Bi": { "quality": 208.98, "proton": 83 , "cn": "铋", "group": "metalloid"},
    "Mc": { "quality": 290   , "proton": 115, "cn": "镆", "group": "metalloid"},

    "O" : { "quality": 15.999, "proton": 8  , "cn": "氧", "group": "nonmetal"},
    "S" : { "quality": 32.06 , "proton": 16 , "cn": "硫", "group": "nonmetal"},
    "Se": { "quality": 78.971, "proton": 34 , "cn": "硒", "group": "nonmetal"},
    "Te": { "quality": 127.60, "proton": 52 , "cn": "碲", "group": "metalloid"},
    "Po": { "quality": 209   , "proton": 84 , "cn": "钋", "group": "metalloid"},
    "Lv": { "quality": 293   , "proton": 116, "cn": "鉝", "group": "metalloid"},

    "F" : { "quality": 18.998, "proton": 9  , "cn": "氟", "group": "halogen"},
    "Cl": { "quality": 35.45 , "proton": 17 , "cn": "氯", "group": "halogen"},
    "Br": { "quality": 79.904, "proton": 35 , "cn": "溴", "group": "halogen"},
    "I" : { "quality": 126.90, "proton": 53 , "cn": "碘", "group": "halogen"},
    "At": { "quality": 210   , "proton": 85 , "cn": "砹", "group": "halogen"},
    "Ts": { "quality": 294   , "proton": 117, "cn": "Ts", "group": "none"},

    "He": { "quality": 4.0026, "proton": 2  , "cn": "氦", "group": "noble"},
    "Ne": { "quality": 20.180, "proton": 10 , "cn": "氖", "group": "noble"},
    "Ar": { "quality": 39.948, "proton": 18 , "cn": "氩", "group": "noble"},
    "Kr": { "quality": 83.798, "proton": 36 , "cn": "氪", "group": "noble"},
    "Xe": { "quality": 131.29, "proton": 54 , "cn": "氙", "group": "noble"},
    "Rn": { "quality": 222   , "proton": 86 , "cn": "氡", "group": "noble"},
    "Og": { "quality": 294   , "proton": 118, "cn": "Og", "group": "none"},
};
